My-Medi/FrontEnd

src/components/MyHome/SideBar.tsx, src/components/MyHome/SimpleBox.tsx, src/layout/HomeLayout.tsx, src/pages/Myhome/MyHome.tsx
fix: 마이홈 반응형 수정
- close #28 
- 마이홈 반응형 코드 수정
* 고정값 calc 삭제
* 간격 수정
- 다음 할 일1
- 다음 할 일2
=> fix: 마이홈 반응형 수정

src/components/Common/layout/Footer.tsx, src/components/MyHome/SideBar.tsx, src/layout/HomeLayout.tsx, src/pages/Myhome/MyHome.tsx
fix: 푸터 하단 빈 공간, 마이홈 공간 수정
- close #30 
- 푸터 수정
- 마이홈 수정
* 패딩값으로 빈공간 표시 
- 다음 할 일1
- 다음 할 일2
=> fix: 푸터 하단 빈 공간, 마이홈 공간 수정

src/assets/MyHome/SideBar/home.svg, src/components/Common/layout/Footer.tsx, src/index.css, tailwind.config.js
fix: 푸터 수정, 테일윈드 config추가
- close #32 
-Footer 길이 피그마에 맞게 수정
- 테일윈드 config 추가 
* footer 길이 수정
* index.css 대신 테일윈드 config 추가
- 다음 할 일1
- 다음 할 일2
=> fix: 푸터 수정, 테일윈드 config추가

src/components/Common/layout/Topbar.tsx, src/components/SignUp/SignUpComplete.tsx, src/components/SignUp/StepSelector.tsx, src/components/SignUp/Stepper.tsx, src/components/SignUp/TermsAgreement.tsx, src/layout/HomeLayout.tsx, src/pages/Signup/SignUp.tsx
- close #39 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> Fix: 회원가입 비율 수정

package-lock.json, package.json, src/components/Common/layout/NavBar.tsx, src/components/Common/layout/Topbar.tsx, src/components/Common/modal/LoginConfirmModal.tsx, src/components/Login/LoginInput.tsx, src/components/SignUp/StepSelector.tsx, src/layout/HomeLayout.tsx, src/pages/Login/LoginPage.tsx
feat: 로그인 모달창
- close #44 
- 로그인 에러 모달창 추가
- navbar 수정 
* 로그인 에러 시 모달창 추가
=> feat: 로그인 모달창

src/assets/MyHome/plus.svg, src/components/Common/layout/Footer.tsx, src/components/Expert/ExpertCategoryPopover.tsx, src/components/Expert/Pagination.tsx, src/components/MyHome/User_MatchingExpert/ExpertCard.tsx, src/components/MyHome/User_MatchingExpert/MatchedExperts.tsx, src/data/matchedExperts.ts, src/pages/Expert/ExpertPage.tsx, src/pages/Myhome/MyHome.tsx
feat: 마이홈 - 메칭 전문가 틀 완성
- close #83 
- 일반 사용자의 마이홈- 매칭 전문가 페이지
* 일반 사용자의 마이홈- 매칭 전문가 페이지
- 다음 할 일1
- 다음 할 일2
=> Feat: 일반 사용자 마이홈 - 매칭 전문가 페이지

src/components/MyHome/MyHomeEdit/ConfirmModal.tsx, src/components/MyHome/MyHomeEdit/EditInfo.tsx, src/components/MyHome/MyHomeEdit/SuccessModal.tsx, src/components/MyHome/ProfileInfo.tsx, src/contexts/AuthContext.tsx, src/pages/Myhome/MyHome.tsx
- close #88 
* 회원정보 수정 페이지
- 비밀번호 보이게 했을 때 아이콘 없음..
=> feat:회원정보 수정 페이지 개발

src/components/Introduce/Common/CTAButton.tsx, src/components/MyHome/Expert_Resume/components/CareerSection.tsx, src/components/MyHome/Expert_Resume/components/CertificateSection.tsx, src/components/MyHome/Expert_Resume/components/RepresentativeSentenceSection.tsx
fix: 이력서 관리 수정
- close #110 
- 이력서 관리 페이지 피그마변경에 따른 수정
* 이력서 관리 페이지 피그마변경에 따른 수정
- 다음 할 일1
- 다음 할 일2
=> fix: 이력서 관리 수정

src/App.tsx, src/apis/userApi/user.ts, src/components/Common/layout/Topbar.tsx, src/components/MyHome/Edit/EditInfo.tsx, src/components/MyHome/Patient/PatientHome.tsx, src/components/MyHome/Profile/ProfileInfo.tsx, src/hooks/tokens/useLoginMutation.ts, src/hooks/users/useUserProfileMutation.ts, src/hooks/users/useUserProfileQuery.ts, src/types/common.ts, src/utils/dateUtils.ts
feat: 사용자 프로필 조회 API 연동
- close #126 
- 사용자 프로필 조회 API 연동
* 사용자 프로필 조회 API 연동
- 다음 할 일1
- 다음 할 일2
=> feat: 사용자 프로필 조회 API 연동

src/apis/axios.ts, src/utils/cookies.ts, src/utils/tokenStorage.ts
fix: 쿠키 토큰 암호하
- close #126 
- 쿠키 토큰 암호하
* 쿠키 토큰 암호하
- 다음 할 일1
- 다음 할 일2
=> fix: 쿠키 토큰 암호하

src/apis/expertApi/expert.ts, src/components/Expert/Card/ExpertCard.tsx, src/hooks/experts/useExpertListQuery.ts, src/hooks/tokens/useLoginMutation.ts, src/pages/Expert/ExpertPage.tsx, src/types/common.ts, src/types/expert.ts, src/types/index.ts
feat: 전문가 페이지 api 연동
- close #133 
- 전문가 페이지 api 연동
- 전문가 로그인 임시 추가
- 다음 할 일1
- 다음 할 일2
=> feat: 전문가 페이지 api 연동

src/components/SignUp/ExpertInputForm.tsx, src/components/SignUp/Stepper.tsx
- close #139 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> fix:signupexpertform

src/App.tsx, src/components/Introduce/Main/AdBanner.tsx, src/contexts/AuthContext.tsx, src/hooks/tokens/useLoginMutation.ts, src/pages/Login/LoginPage.tsx, src/utils/tokenStorage.ts
fix: 로그인 유지버튼 기능 + 디자인수정
- close #142 
- 로그인 유지버튼 기능 + 디자인수정
- 다음 할 일1
- 다음 할 일2
=> fix: 로그인 유지버튼 기능 + 디자인수정

src/components/Introduce/Main/AdBanner.tsx
fix: 버튼 위치 수정
- close #142 
- 버튼 위치 수정
* 버튼 위치 수정
- 다음 할 일1
- 다음 할 일2
=> fix: 버튼 위치 수정

src/index.css
feat: 커스텀 스크롤UI
- close #149 
- [커스텀 스크롤UI
- 다음 할 일1
- 다음 할 일2
=> feat: 커스텀 스크롤UI

src/App.tsx, src/components/Common/LoadingSpinner.tsx, src/components/Common/layout/NavBar.tsx, src/components/Common/layout/Topbar.tsx, src/components/Expert/Intro/Pagination.tsx, src/components/Expert/Modal/ExpertDetailModal.tsx, src/components/Introduce/AIHealthCare/AIHealthCareIntroPage.tsx, src/components/Introduce/Calendar/CalendarIntroPage.tsx, src/components/Introduce/ExpertMatching/ExpertMatchingIntroPage.tsx, src/components/Introduce/Main/AdBanner.tsx, src/components/Introduce/Main/CTAButton.tsx, src/components/Introduce/MedicalReport/MedicalReportIntroPage.tsx, src/hooks/useModalScrollLock.ts, src/layout/HomeLayout.tsx, src/pages/Introduce/IntroducePage.tsx, src/pages/Login/LoginPage.tsx, src/pages/Signup/SignUp.tsx, src/router/index.tsx
- close #152 
- UI 간격 수정
* UI 간격 수정
- 다음 할 일1
- 다음 할 일2
=> fix: UI 간격 수정

src/components/Common/CustomCheckboxButton.tsx, src/components/HealthCareRequest/RequestForm.tsx, src/components/HealthCheckupResultInput/AdditionalExamSection.tsx, src/components/HealthCheckupResultInput/HealthCheckupForm.tsx, src/components/HealthCheckupResultInput/RoundSelector.tsx, src/components/MyHome/Edit/EditInfo.tsx
- close #155 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> fix: 건강검진입력페이지 수정

src/components/HealthCheckupResultInput/HealthCheckupForm.tsx
- close #155 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> fix: healthCheckupForm 수정

src/components/HealthCheckupResultInput/HealthCheckupForm.tsx, src/components/SignUp/Info.tsx, src/components/SignUp/SignUpComplete.tsx, src/pages/Signup/SignUp.tsx, src/utils/dateUtils.ts
fix: 회원가입 연동 코드 수정
- close #161 
- 회원가입 연동 코드 수정
* 회원가입 연동 코드 수정
- 다음 할 일1
- 다음 할 일2
=> fix: 회원가입 연동 코드 수정

pnpm-lock.yaml, src/components/Common/ProtectedRoute.tsx, src/components/PatientManagement/consultReservationModal/Calendar.tsx, src/components/SignUp/ExpertInputForm.tsx, src/pages/Login/LoginPage.tsx, src/router/index.tsx
fix: 에러 수정
- close #169 
- 에러 수정
* 병합 중 생긴 오류사항 수정
- 다음 할 일1
- 다음 할 일2
=> fix: 에러 수정

src/apis/expertApi/expert.ts, src/apis/imageApi/image.ts, src/components/Alarm/NotificationList.tsx, src/components/Common/ImageUpload.tsx, src/components/Common/MultipleImageUpload.tsx, src/components/SignUp/ExpertInputForm.tsx, src/components/SignUp/Info.tsx, src/hooks/experts/useSignUpMutation.ts, src/hooks/images/useImageUploadMutation.ts, src/hooks/notifications/useExpertNotificationsInfiniteQuery.ts, src/hooks/notifications/useNotificationManager.ts, src/hooks/notifications/useUserNotificationsInfiniteQuery.ts, src/pages/Signup/SignUp.tsx, src/types/expert.ts
- close #174 
- 전문가 회원가입 API 연동
- 전문가 알림 에러 수정
* 전문가 회원가입 API 연동
- 다음 할 일1
- 다음 할 일2
=> feat: 전문가 회원가입 API 연동

src/components/HealthCheckupResultInput/HealthCheckupForm.tsx
feat: bmi수치 자동 입력 로직
- close #181 r
-  bmi수치 자동 입력 로직
* 사용자의 키/몸무게 값을 받아 구글에 정의된 bmi수치를 기준으로 자동 BMI 수치 자동 입력 
- 다음 할 일1
- 다음 할 일2
=> feat: bmi수치 자동 입력 로직

src/apis/expertApi/detail.ts, src/apis/expertApi/list.ts, src/apis/expertApi/matching.ts, src/apis/userApi/user.ts, src/components/Alarm/NotificationItemSkeleton.tsx, src/components/Alarm/NotificationList.tsx, src/components/Expert/Card/ExpertCard.tsx, src/components/Expert/Card/ExpertCardSkeleton.tsx, src/components/Expert/Intro/Pagination.tsx, src/components/Expert/Modal/ConfirmRequestModal.tsx, src/components/Expert/Modal/ExpertDetailModal.tsx, src/components/Expert/Modal/RequestModal.tsx, src/components/HealthCareRequest/RequestForm.tsx, src/components/MyHome/Edit/EditInfo.tsx, src/components/MyHome/Layout/SimpleBox.tsx, src/components/MyHome/Matching/ExpertCard.tsx, src/components/MyHome/Matching/MatchedExperts.tsx, src/components/MyHome/Patient/MyConstantMedical.tsx, src/components/MyHome/Patient/PatientHome.tsx, src/components/MyHome/Profile/ProfileInfo.tsx, src/components/RequestHealthCare/HealthCareCardSkeleton.tsx, src/components/RequestHealthCare/RequestHealthCare.tsx, src/hooks/experts/mutations/useRequestConsultationMutation.ts, src/pages/Expert/ExpertPage.tsx, src/types/common.ts, src/types/expert/common.ts, src/types/expert/detail.ts, src/types/expert/list.ts, src/types/healthProposal.ts, src/utils/phoneUtils.ts
fix: API 수정에 따른 값 수정
- close #190 
- API 수정에 따른 값 수정
* API request,response 수정에 따른 매핑, dto 수정입니다.
- 다음 할 일1
- 다음 할 일2
=> fix: API 수정에 따른 값 수정

src/apis/expertApi/list.ts, src/apis/expertApi/matching.ts, src/apis/userApi/user.ts, src/components/Common/layout/NavBar.tsx, src/components/Expert/Modal/ConfirmRequestModal.tsx, src/components/Expert/Modal/ExpertDetailModal.tsx, src/components/Expert/Modal/ExpertDetailSkeleton.tsx, src/components/Expert/Modal/RequestModal.tsx, src/components/Expert/Modal/SuccessModal.tsx, src/components/MyHome/Edit/ConfirmModal.tsx, src/components/MyHome/Edit/SuccessModal.tsx, src/components/MyHome/Matching/CancelRequestConfirmModal.tsx, src/components/MyHome/Matching/MatchedExperts.tsx, src/contexts/AuthContext.tsx, src/hooks/experts/mutations/useRequestConsultationMutation.ts, src/hooks/experts/queries/useExpertListQuery.ts, src/hooks/notifications/expert/query/useExpertNotificationsQuery.ts, src/hooks/notifications/useNotificationManager.ts, src/hooks/notifications/user/query/useUserNotificationsQuery.ts, src/pages/Expert/ExpertPage.tsx, src/pages/Myhome/MyHome.tsx
- close #203 
- 전문가 모달 오류 수정
* 전문가 모달에서 모달이 순회하는 오류 수정
* 회원정보 수정 모달 폰트 수정 
- 다음 할 일1
- 다음 할 일2
=> fix: 전문가 모달 오류 수정

src/apis/expertApi/profile.ts, src/apis/expertApi/resume.ts, src/apis/tokenApi/token.ts, src/components/Expert/Card/ExpertCard.tsx, src/components/MyHome/Edit/EditInfo.tsx, src/hooks/tokens/useTokenReissueMutation.ts, src/pages/Expert/ExpertPage.tsx, src/utils/resumeUtils.ts
fix: APi 엔드포인트 및 매핑 값 수정
- close #206 
- APi 엔드포인트 및 매핑 값 수정
* APi 엔드포인트 및 매핑 값 수정
* 전문가 카드, 내 프로필 수정, 전문가 이력서 관리 부분
- 다음 할 일1
- 다음 할 일2
=> fix: APi 엔드포인트 및 매핑 값 수정

src/apis/healthCheckupApi/healthCheckup.ts, src/components/HealthCheckupResultInput/AdditionalExamSection.tsx, src/components/HealthCheckupResultInput/HealthCheckupForm.tsx, src/hooks/healthCheckup/useHealthReportMutation.ts, src/hooks/healthCheckup/useHealthReportQuery.ts
- close #215 
> 참고 링크
- 없으면 지워주세요.
* 건강 리포트 api 연동- 수정, 생성, 조회
=> feat: 건강 리포트 api 연동- 수정, 생성, 조회

src/components/Common/layout/NavBar.tsx, src/components/MedicalReportLLM/MedicalReport.tsx
- close # Issue Number
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> Feat: LLM 페이지 연결 및 건강검진 횟수에 따른 페이지 연결

src/apis/healthCheckupApi/healthCheckup.ts, src/components/HealthCheckupResultInput/HealthCheckupForm.tsx, src/types/healthCheckupForm.tsx
- close #217 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> feat: 건강리포트api 연동

src/apis/userApi/user.ts, src/components/Common/FileUploadSection.tsx, src/components/Introduce/Main/AdBanner.tsx, src/components/MyHome/Resume/CertificateSection.tsx, src/components/RequestHealthCare/DetailModal/ReportSummary.tsx, src/components/RequestHealthCare/HealthCareCard.tsx, src/components/SignUp/ExpertInputForm.tsx
fix: 이미지 업로드 부분 UI 수정 및 컴포넌트화
- close #227 
-  이미지 업로드 부분 UI 수정 및 컴포넌트화
*  이미지 업로드 부분 UI 수정
* 여러 페이지에서 공용적으로 사용하기때문에 컴포넌트화 시켰습니다.
- 다음 할 일1
- 다음 할 일2
=> fix: 이미지 업로드 부분 UI 수정 및 컴포넌트화

src/apis/consultationApi/consultation.ts, src/components/Common/FileUploadSection.tsx, src/components/Common/layout/NavBar.tsx, src/components/Expert/Modal/ExpertDetailModal.tsx, src/components/HealthCheckupResultInput/HealthCheckupForm.tsx, src/components/PatientManagement/memberCardModel/memberCardModal.tsx, src/components/RequestHealthCare/DetailModal/DetailModal.tsx, src/components/RequestHealthCare/DetailModal/ReportSummary.tsx, src/components/RequestHealthCare/HealthCareCard.tsx, src/hooks/consultation/expert/queries/useExpertReportSummary.ts, src/hooks/consultation/expert/queries/useExpertUserReportByRound.ts, src/hooks/users/queries/useUserProfileQuery.ts, src/types/reportSummary.ts
feat: 건강검진 요약 부분 API 연동
- close #232 
- 건강검진 요약 부분 API 연동
* 건강검진 요약 부분 API 연동
* UI 변경 부분 수정
- 다음 할 일1
- 다음 할 일2
=> feat: 건강검진 요약 부분 API 연동

src/components/HealthCareRequest/ConfirmModal.tsx
- close #
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> fix:전문가요청 모달 수정

src/apis/expertApi/consultations.ts, src/apis/expertApi/matching.ts, src/components/Expert/Filter/ExpertCategoryFilter.tsx, src/components/Expert/Modal/ExpertDetailModal.tsx, src/components/HealthTerms/HealthTermsInfo.tsx, src/components/MyHome/Expert/ExpertHome.tsx, src/components/MyHome/Expert/ExpertSchedule.tsx, src/components/PatientManagement/memberCard.tsx, src/components/PatientManagement/memberCardModel/memberCardModal.tsx, src/components/PatientManagement/memberList.tsx, src/hooks/experts/queries/useAcceptedConsultations.ts
fix: 작동하지 않은 UI 수정
- close #240 
- 작동하지 않은 UI 수정
* 작동하지 않은 UI 수정
* 전문가 마이홈, 거절당한 전문가에게 요청버튼 비활성화, 전문가는 일반유저가 최근 건강검진이 없으면, 건강검진 리포트 보기 버튼 비활성화
- 다음 할 일1
- 다음 할 일2
=> fix: 작동하지 않은 UI 수정

src/components/SignUp/Info.tsx
- close #239 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> Fix:회원가입정보입력수정

src/components/SignUp/Info.tsx
- close #243 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> fix:회원가입정보간격수정

src/pages/MedicalReportPage.tsx
- close #246 
> 참고 링크
- 없으면 지워주세요.
- 다음 할 일1
- 다음 할 일2
=> feat:건강리포트회차api 연동

src/apis/axios.ts, src/apis/expertApi/matching.ts, src/components/Expert/Modal/ExpertDetailModal.tsx, src/components/HealthTerms/HealthTermsInfo.tsx, src/components/Introduce/AIHealthCare/AIHealthCareIntroPage.tsx, src/components/Introduce/ExpertMatching/ExpertMatchingIntroPage.tsx, src/components/Introduce/Main/AdBanner.tsx, src/components/Introduce/MedicalReport/MedicalReportIntroPage.tsx, src/hooks/experts/mutations/useRequestConsultationMutation.ts
feat: API 에러 수정
- close #248 
- 전문가 요청 보내기 부분 API 에러 수정
*  전문가 요청 보내기 부분 API 에러 수정
* 거절된 요청은 버튼을 막아뒀는데 오류로 다시 열었습니다.
- 다음 할 일1
- 다음 할 일2
=> feat: API 에러 수정

src/apis/userApi/user.ts, src/components/Expert/Modal/RequestModal.tsx, src/components/HealthCheckupResultInput/HealthCheckupForm.tsx, src/components/MyHome/Profile/ProfileInfo.tsx, src/components/MyMedicalReport/BottomButtons.tsx, src/components/MyMedicalReport/body/Cards/LeftPatientCard.tsx, src/components/MyMedicalReport/body/Cards/PatientCardList.tsx, src/components/MyMedicalReport/body/Cards/TooltipForTerm.tsx, src/components/MyMedicalReport/body/Chart.tsx, src/pages/MedicalReportLLM/MedicalReportLLMPage.tsx, src/pages/MedicalReportPage.tsx
fix: 새로운 APi 연동 UI 에러 수정
- close #275 
- 새로운 APi 연동 UI 에러 수정
* 새로운 APi 연동 UI 에러 수정
- 다음 할 일1
- 다음 할 일2
=> fix: 새로운 APi 연동 UI 에러 수정
